### ISSUE TITLE
merge two abc material files

### ISSUE THREAD

**Issue by elliottbb** [alembic/cask#2] opened 2016-12-06 12:29 UTC
i've been trying to use cask to merge two alembic files that contain only materials in.

```
def run(fileA, fileB, fileOut):
	a = cask.Archive(fileA)
	b = cask.Archive(fileB)
	
	o = cask.Archive()
	o.top.children["materials"] = cask.Material()

	for i in a.top.children['materials'].children:
		o.top.children['materials'].children[i] = a.top.children['materials'].children[i]

	for i in b.top.children['materials'].children:
		o.top.children['materials'].children[i] = b.top.children['materials'].children[i]

	o.write_to_file(fileOut)
```

when executing this, it errors with:

Error setting value on .terminals: <imath.StringArray object at 0x23143d0> <class 'alembic.Abc.OArrayProperty'>
No registered converter was able to produce a C++ rvalue of type std::tr1::shared_ptr<Alembic::Abc::v7::TypedArraySample<Alembic::Abc::v7::StringTPTraits> > from this Python object of type StringArray
Error setting value on aov_names: <imath.StringArray object at 0x2393ec0> <class 'alembic.Abc.OArrayProperty'>
No registered converter was able to produce a C++ rvalue of type std::tr1::shared_ptr<Alembic::Abc::v7::TypedArraySample<Alembic::Abc::v7::StringTPTraits> > from this Python object of type StringArray
Error setting value on .connections: <imath.StringArray object at 0x2390130> <class 'alembic.Abc.OArrayProperty'>
No registered converter was able to produce a C++ rvalue of type std::tr1::shared_ptr<Alembic::Abc::v7::TypedArraySample<Alembic::Abc::v7::StringTPTraits> > from this Python object of type StringArray
Error setting value on .interface: <imath.StringArray object at 0x2390130> <class 'alembic.Abc.OArrayProperty'>
No registered converter was able to produce a C++ rvalue of type std::tr1::shared_ptr<Alembic::Abc::v7::TypedArraySample<Alembic::Abc::v7::StringTPTraits> > from this Python object of type StringArray
Error setting value on .terminals: <imath.StringArray object at 0x2390130> <class 'alembic.Abc.OArrayProperty'>
No registered converter was able to produce a C++ rvalue of type std::tr1::shared_ptr<Alembic::Abc::v7::TypedArraySample<Alembic::Abc::v7::StringTPTraits> > from this Python object of type StringArray
Error setting value on aov_names: <imath.StringArray object at 0x2398d00> <class 'alembic.Abc.OArrayProperty'>
No registered converter was able to produce a C++ rvalue of type std::tr1::shared_ptr<Alembic::Abc::v7::TypedArraySample<Alembic::Abc::v7::StringTPTraits> > from this Python object of type StringArray
Error setting value on .connections: <imath.StringArray object at 0x2398f30> <class 'alembic.Abc.OArrayProperty'>
No registered converter was able to produce a C++ rvalue of type std::tr1::shared_ptr<Alembic::Abc::v7::TypedArraySample<Alembic::Abc::v7::StringTPTraits> > from this Python object of type StringArray
Error setting value on .interface: <imath.StringArray object at 0x7f596a88c280> <class 'alembic.Abc.OArrayProperty'>
No registered converter was able to produce a C++ rvalue of type std::tr1::shared_ptr<Alembic::Abc::v7::TypedArraySample<Alembic::Abc::v7::StringTPTraits> > from this Python object of type StringArray

further down the line, when i try to use the merged file, arnold errors with:

Invalid sample index: -1, should be between 0 and 4294967295

im using alembic 1.5.8 and the default branch of cask.

any ideas how i can resolve these errors?

many thanks,

elliott

**Comment by rsgalloway** [comment] 2016-12-08 20:04
Looks like it's able to create the properties, but not set any values, maybe due to an inability to correctly map the value to the correct property class. Are you able to share an example file at all?

**Comment by elliottbb** [comment] 2016-12-09 09:59
hey, 

attached are two individual abc files, each containing just a single shader, plus the script im using to try and stitch them together.

[cask_merge.tar.gz](https://github.com/alembic/cask/files/641768/cask_merge.tar.gz)

all the best,

elliott

**Comment by rsgalloway** [comment] 2016-12-13 00:56
Hmm, I ran your code and it's working for me, i.e. I can't reproduce those errors (using alembic 1.5.7, cask 1.0.0). I get an abc file that has both materials in it, including all the params:

```
> abctree out.abc 
ABC               
 `--materials     
     |--blueSG    
     `--redSG  
```

The timesampling thing is an issue, though. I think you'll need to create and add a new timesampling object to the output archive though. o.add_timesampling(). 

Maybe try pulling from the cask repo to make sure you're using the latest?

**Comment by rsgalloway** [comment] 2018-06-11 20:26
This is a year and a half old, closing for now.

**Closed as completed by rsgalloway** 2018-06-11 20:26 UTC
